### ISSUE TITLE
[config] allow partials/fragments

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#232]

**Comment by jonnymbgood** [comment]
```yaml
type: URL
address: http://example.org
statusCode: 200
```

```yaml
type: AWS
accountID: 1234
region: us-east-2
role: my-role
AccessKeyID: xxx
EncryptedSecretAccessKey: yyy
```

```yaml
type: Kubernetes
server: api server
encryptedToken: xxx
```

**Comment by jonnymbgood** [comment]
We can reference partials by putting a string where the object would regularly go. 
```yaml
type: LoginAWS
source: /aws/primary
destination:
  ...
```

A few questions. Should the file extension be used or required in the reference (`/aws/primary.yaml`)? Should it error on type mismatch?

@thuey
