### ISSUE TITLE
[meta] syntax for command parameters

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#249]
CheckKubernetes - specify namespace
TriggerJenkinsJob - specify job parameters

**Comment by jonnymbgood** [comment]
As discussed today the best compromise may be simple key/value pairs (i.e.`key=value`) and make the keys always configurable by the customer to avoid potential future collisions.

**Comment by thuey** [comment]
It seems like there are a couple ways to do this:
1. Configure parameters for a type, and then reference those parameters in the configuration. We would need a special delimiter to indicate where the parameters are coming from. Something like this:
```
type: TriggerJenkinsJob
name: deploy
server: $P_server
jobParameters:
  TAG: $P_tag
parameters:
  server:
    default: https://localhost
  tag: {}
```
2. In-line the parameter configuration with the property that needs to be set. We would need to check if the value is a raw type or an object. Something like this:
```
type: TriggerJenkinsJob
name: deploy
server:
  param: server
  default: https://localhost
jobParameters:
  TAG:
    param: tag
```

@jonnymbgood Thoughts?

**Comment by thuey** [comment]
@jonnymbgood thoughts?

**Comment by jonnymbgood** [comment]
What about...

Most of the time we will have all or nothing parameterized, so the command should be able to have an implicit pointer to the parameters.

```yaml
type: TriggerJenkinsJob
name: deploy
server: https://localhost
parameters:
  - key: tag # implicit type: Parameter and source: parameter here
  - key: env
    default: dev
```

For times where we allow another field to be parameterized we could embed a `Parameter` object
```yaml
type: TriggerJenkinsJob
name: deploy
server:
  type: Parameter # Not needed? implicit?
  source: parameter # does not point to the parameters object below, but to the source. Could also be env?
  key: server
  default: https://localhost
parameters: # An array of Parameter types
  - key: tag # implicit type: Parameter and source: parameter here again
  - key: env
    default: dev
```

If we wanted to pull the parameter from the server we may be able to encode that in the source field, or maybe use a `RemoteParameter(s)` type or something as another field.

@thuey thoughts?

**Comment by thuey** [comment]
I'd prefer to just be explicit about it. I don't like that there are two ways for a parameter to be configured. Users might want to configure explicit parameters anyway in order to address case differences (eg tag vs TAG).

At this point, my preference is for the second option I proposed, and we could introduce some of the features you talked about later, like pulling from env and remote.

**Comment by jonnymbgood** [comment]
Based on our discussions offline, I think we settled on:
```yaml
type: Foo
foo:
  thing:
    one: bar
  another:
    thing: 2
parameters:
  - name: vbr
     path: foo.thing.one # will only override bar if set
  - name: zbx
     path: foo.another.opt # sets a key that isn't set in the config but exists in the type
     required: true # command will fail if this is not set
```

Command: `/please execute this zbx=snuggle pby=jelly`

* `foo.another.opt` is set to `snuggle`
* `foo.thing.one` remains `bar`
* Will `pby be ignored and a warning shown? Or should it error?
