### ISSUE TITLE
[server] add users/roles blocks to the config

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#44]
```
users:
  username:
    roles: ['a', 'b']
roles:
  rolename:
    permissions:
      - action: *
        targetType: *
        targetID: *
```
